name: Deploy to ECS-EC2 

on:
  workflow_dispatch:  # Allow manual trigger of the deployment workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Latest Image URI
        id: get_image_uri
        run: |
          IMAGE_TAG=$(aws ecr describe-images --repository-name demo-app-repo \
                    --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' --output text)
          if [ -z "$IMAGE_TAG" ]; then
            echo "Error: Unable to fetch the latest image tag."
            exit 1
          fi
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/demo-app-repo:$IMAGE_TAG"
          echo "LATEST_IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Get Subnet ID
        id: get_subnet_id
        run: |
          SUBNET_ID=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=your-vpc-name" --query "Vpcs[0].VpcId" --output text)" --query "Subnets[0].SubnetId" --output text)
          echo "SUBNET_ID=$SUBNET_ID" >> $GITHUB_ENV

      - name: Get Security Group ID
        id: get_sg_id
        run: |
          SG_ID=$(aws ec2 describe-security-groups --filters "Name=vpc-id,Values=$(aws ec2 describe-vpcs --filters "Name=tag:Name,Values=your-vpc-name" --query "Vpcs[0].VpcId" --output text)" "Name=group-name,Values=your-sg-name" --query "SecurityGroups[0].GroupId" --output text)
          echo "SG_ID=$SG_ID" >> $GITHUB_ENV

      - name: Describe Current ECS Task Definition
        id: describe_task
        run: |
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition demo-app-task)
          echo "$TASK_DEFINITION" > current_task_definition.json

      - name: Create New Task Definition JSON
        id: create_task_def
        run: |
          NEW_TASK_DEF=$(jq --arg IMAGE_URI "${{ env.LATEST_IMAGE_URI }}" \
            '.taskDefinition | 
            .containerDefinitions[0].image=$IMAGE_URI |
            del(.revision, .taskDefinitionArn, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
            current_task_definition.json)
          echo "$NEW_TASK_DEF" > new_task_definition.json

      - name: Register New ECS Task Definition
        id: register_task_def
        run: |
          TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://new_task_definition.json \
                                --query "taskDefinition.taskDefinitionArn" --output text)
          if [ $? -ne 0 ]; then
            echo "Error: Failed to register new task definition."
            exit 1
          fi
          echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN" >> $GITHUB_ENV

      - name: Deploy New Task Definition to ECS Service
        run: |
          aws ecs update-service \
            --cluster example-ecs-cluster \
            --service example-ecs-service \
            --force-new-deployment \
            --task-definition ${{ env.TASK_DEFINITION_ARN }} \
            --network-configuration "awsvpcConfiguration={subnets=[${{ env.SUBNET_ID }}],securityGroups=[${{ env.SG_ID }}],assignPublicIp=ENABLED}"
          if [ $? -ne 0 ]; then
            echo "Error: Failed to update ECS service."
            exit 1
          fi

      - name: Cleanup Temporary Files
        run: |
          rm -f current_task_definition.json new_task_definition.json
